// This purely exports the data for the app.
export const data = {
  bio: {
    name: "Jordan Baumgardner",
    tagline: "Software Engineer",
    email: "career@jordanbaumgardner.com",
    website: "https://jordanbaumgardner.com",
    github: "https://github.com/jordanbaumwx",
    objective:
      "Software Engineer with over 5 years professional experience performing development of meteorological related software systems including hardware data collection and manipulation, algorithms and display systems for delivery at private entities, international weather services and international airport agencies, in addition to development of several web-based applications.",
  },
  skills: [
    "Python",
    "Go",
    "SQL",
    "Node.JS",
    "React",
    "GraphQL",
    "TypeScript",
    "JavaScript",
  ],
  positions: [
    {
      id: "1",
      title: "Software Engineer",
      company: "Radiometrics Corporation",
      startDate: "2019-09-09",
      endDate: null,
      employmentType: "FULL_TIME",
      location: "Boulder, Colorado",
      achievements: [
        "Guided software design decisions for weather instrumentation to bring a refreshed and modernized software product to market.",
        "Worked with customers on software changes and get feedback on design improvements and customer needs.",
        "Used Go Programming Language, React, PSQL and Python as code base foundation.",
        "Learned Docker to help facilitate writing cross platform code fast and efficiently without introducing Operating System complications.",
        "Managed Amazon Web Services to facilitate a code build process and increase access security.",
      ],
    },
    {
      id: "2",
      title: "Meteorological Programmer",
      company: "Weather Decision Support Systems, International",
      startDate: "2016-01-03",
      endDate: "2019-09-08",
      employmentType: "FULL_TIME",
      location: "Norman, Oklahoma",
      achievements: [
        "Developed graphical interface and other software to playback various meteorological datasets in AWIPS II for the City of Buenos Aires modernization project.",
        "Performed rewrite and upgrades to a data integration, processing, and display system delivered to international airport locations that ingests radiometers, sodars, and wind profilers to provide wind shear alerts and nowcasting products.",
        "Developed software system to access and transfer data from a US network of radiometers, sodars, and wind profilers to Amazon Web Services, and format these data for inclusion in the National Mesonet Program.",
        "Performing rewrite of radiometer control software which involved understanding current configuration and learning new coding language.",
        "Developed WDSS company web page including blogging and Photoshop work.",
        "Attended 12-week Python class and attained Python Certified Associate Programmer certification.",
      ],
    },
    {
      id: "3",
      title: "Production Assistant",
      company: "KCIM and Keystone Broadcasting",
      startDate: "2016-08-01",
      endDate: "2018-12-08",
      employmentType: "CONTRACT",
      location: "Ardmore, Oklahoma",
      achievements: [
        "Worked with a handheld Cannon camcorder to provide solo camera work for a livestream of Sulphur Bulldog Football.",
        "Assisted in created pre-recorded video segments and other graphics.",
      ],
    },
    {
      id: "4",
      title: "App Developer",
      company: "Self-Employed",
      startDate: "2011-11-01",
      endDate: "2019-05-01",
      employmentType: "SELF_EMPLOYED",
      location: "Remote",
      achievements: [
        "Designed and maintained app for Sulphur Public Schools in iOS and Android.",
        "Designed and maintained a weather forecasting app, StormCast, using DarkSky API.",
        "Designed and maintained a college football recruiting app, Reload Status: The Fans Recruiting Network.",
      ],
    },
    {
      id: "5",
      title: "Production Assistant",
      company: "SoonerVision",
      startDate: "2014-08-31",
      endDate: "2017-05-15",
      employmentType: "STUDENT_PT",
      location: "Norman, Oklahoma",
      achievements: [
        "Performed editing of videos using Avid Video Editor for both television and web broadcast.",
        "Operated EVS instant replay system, LSM Connect, and Chyron graphics tools in live production.",
      ],
    },
    {
      id: "6",
      title: "Student Forecaster",
      company: "Oklahoma Weather Lab",
      startDate: "2015-08-20",
      endDate: "2016-05-15",
      employmentType: "STUDENT_PT",
      location: "Norman, Oklahoma",
      achievements: [
        "Prepared and wrote forecasts and forecast discussions for Oklahoma and Key West, Florida.",
        "Wrote and recorded radio hits for Key West, Florida containing daily weather information.",
      ],
    },
    {
      id: "7",
      title: "IT Assistant and Video Production Manager",
      company: "Sulphur Public Schools",
      startDate: "2012-05-20",
      endDate: "2016-02-20",
      employmentType: "PART_TIME",
      location: "Sulphur, Oklahoma",
      achievements: [
        "Diagnosed and solved technical problems in school network containing ~800 PCs.",
        "Coordinated audio and video presentations for all basketball games with adjustments made on the fly.",
        "Filmed high school football games for the purpose of coach and training review. ",
      ],
    },
  ],
};
